from openai import OpenAI
from app.core.config import settings
import json
from typing import Dict, Any

class AIService:
    @staticmethod
    def get_client():
        if settings.ACTIVE_AI_PROVIDER.upper() == "NVIDIA":
            return OpenAI(
                api_key=settings.NVIDIA_API_KEY,
                base_url="https://integrate.api.nvidia.com/v1"
            )
        else:
            return OpenAI(
                api_key=settings.GEMINI_API_KEY,
                base_url="https://generativelanguage.googleapis.com/v1beta/openai/"
            )

    @staticmethod
    def generate_insights(analysis_results: Dict[str, Any]) -> str:
        # Filter out raw images
        safe_results = {k: v for k, v in analysis_results.items() if k != 'visuals'}
        context_data = json.dumps(safe_results, indent=2)
        
        prompt = f"""
You are a Senior Data Analyst and Senior Data Scientist. Your goal is to analyze the provided dataset intelligence and generate a highly specific, consultant-grade business report.

## YOUR MISSION
You have been provided with deterministic, pre-computed findings generated by our native Python engine (including dataset profiles, target detection, ML strategy, and discovered segment insights).
Your job is to read these exact numbers and output a highly specific business report. 
DO NOT describe the dataset structurally ("The dataset has 10 columns"). DO explain the business meaning ("Google Search drives 58% of acquisition").

## BANNED PHRASES
Do not use generic phrases like:
- "The dataset is clean/dirty."
- "Collect more data."
- "Build predictive models."
- "Suitable for classification/regression."
- "Use data-driven decisions."
Every insight must be specific, numerical, and tied to the exact data provided.

## REPORT STRUCTURE
You must follow this exact markdown structure (the PDF renderer expects these exact headers):

# Page 3: Business Insights
Write 4 sub-sections:
## Top 5 Key Insights
(5 bullet points. Must include actual numbers/percentages from the data. E.g., "The 25-34 age group dominates at 42%.")
## Trends
(Identify temporal or numerical trends)
## Risks
(Identify anomalies, bottom categories, or sparse data risks)
## Opportunities
(Actionable business opportunities based on the insights)

# Page 4: Machine Learning Strategy
Write 4 sub-sections:
## Recommended Models
(List the exact models recommended by the python engine and EXPLAIN WHY they were chosen based on problem type and data size)
## Target Selection
(State the detected target variable and EXPLAIN WHY it is a good target for business prediction)
## Feature Importance
(Explain which features are most predictive or important and WHY)
## Training Considerations
(Explain what needs to be done before training, e.g., handling specific outliers or missing data)

# Page 5: Executive Recommendations
Write 3 sub-sections:
## Actions
(List 3 highly specific actions tied to the data)
## Business Impact
(Explain the expected ROI or impact of those actions)
## Next Steps
(Immediate technical or business steps)

## INPUT DATA
{context_data}
"""
        try:
            client = AIService.get_client()
            import time
            max_retries = 3
            last_error = None
            
            for attempt in range(max_retries):
                try:
                    response = client.chat.completions.create(
                        model=settings.AI_MODEL_NAME,
                        messages=[{"role": "user", "content": prompt}],
                    )
                    return response.choices[0].message.content
                except Exception as e:
                    last_error = str(e)
                    if ("503" in last_error or "429" in last_error) and attempt < max_retries - 1:
                        time.sleep(3 * (attempt + 1))
                        continue
            return f"Failed to generate AI insights due to an error: {last_error}"
        except Exception as e:
            return f"Failed to generate AI insights due to an error: {str(e)}"

    @staticmethod
    def chat_with_data(messages: list, context_data: Dict[str, Any]) -> str:
        safe_results = {k: v for k, v in context_data.items() if k != 'visuals' and k != 'ai_insights'}
        context_str = json.dumps(safe_results, indent=2)
        
        system_prompt = {
            "role": "system",
            "content": f"You are a Senior Data Analyst assisting a user. Use the following statistical summary to answer their questions specifically and numerically.\n\nDATASET SUMMARY:\n{context_str}"
        }
        
        full_messages = [system_prompt] + messages
        try:
            client = AIService.get_client()
            response = client.chat.completions.create(
                model=settings.AI_MODEL_NAME,
                messages=full_messages,
            )
            return response.choices[0].message.content
        except Exception as e:
            return f"Error connecting to AI: {str(e)}"
