from openai import OpenAI
from app.core.config import settings
import json
from typing import Dict, Any

class AIService:
    @staticmethod
    def get_client():
        if settings.ACTIVE_AI_PROVIDER.upper() == "NVIDIA":
            return OpenAI(
                api_key=settings.NVIDIA_API_KEY,
                base_url="https://integrate.api.nvidia.com/v1"
            )
        else:
            # Default to Gemini's OpenAI-compatible endpoint
            return OpenAI(
                api_key=settings.GEMINI_API_KEY,
                base_url="https://generativelanguage.googleapis.com/v1beta/openai/"
            )

    @staticmethod
    def generate_insights(analysis_results: Dict[str, Any]) -> str:
        """
        Passes the statistical findings to the selected AI model to generate natural language insights.
        """
        # We only pass a subset of data to avoid exceeding context window
        # For large correlation matrices, we could filter it down, but for standard datasets it's fine.
        
        # We filter out the 'visuals' key because it contains raw image bytes which are not JSON serializable.
        safe_results = {k: v for k, v in analysis_results.items() if k != 'visuals'}
        context_data = json.dumps(safe_results, indent=2)
        
        prompt = f"""
You are a top-tier Business Intelligence Consultant (think McKinsey, Tableau, Power BI).

The objective is to explain the provided dataset statistics to a non-technical CEO or Business Manager.
You must abandon all dense "consulting terminology" and academic writing. Speak naturally, clearly, and directly.
The final output must be highly readable, concise, and perfectly formatted for a visual dashboard report.

## YOUR MISSION
You have been provided with deterministic, pre-computed findings generated by our native Python Insight Engine (`engine_insights`).
The PDF report has already displayed the raw scores, KPI cards, and visual charts. Your job is to extract the pure business value in short, punchy bullet points.

## REPORT STRUCTURE
Keep the report extremely neat and clean. Use these exact headers:

# Top 5 Key Insights
Extract the 5 most important facts from the data (e.g., "Area is the strongest predictor of price."). Use short bullet points.

# AI Executive Summary
Keep this to 5-8 bullet points maximum. Use this structure:
* **What we found**: [insight]
* **Why it matters**: [business impact]
* **Recommended action**: [action]

# Business Recommendations
Generate highly actionable, practical recommendations based on the target variable or data issues.

# Executive Takeaway
A short one-paragraph final conclusion explaining what the data reveals, what actions should be taken, and the expected business value.

Do NOT invent statistics. Use the `engine_insights` as your factual foundation.

## INPUT DATA
{context_data}
"""
        
        try:
            client = AIService.get_client()
            
            if settings.ACTIVE_AI_PROVIDER.upper() == "NVIDIA" and not settings.NVIDIA_API_KEY:
                return "NVIDIA API key is not configured. AI insights are currently unavailable."
            elif settings.ACTIVE_AI_PROVIDER.upper() == "GEMINI" and not settings.GEMINI_API_KEY:
                return "Gemini API key is not configured. AI insights are currently unavailable."
                
            import time
            max_retries = 3
            last_error = None
            
            for attempt in range(max_retries):
                try:
                    response = client.chat.completions.create(
                        model=settings.AI_MODEL_NAME,
                        messages=[{"role": "user", "content": prompt}],
                    )
                    return response.choices[0].message.content
                except Exception as e:
                    last_error = str(e)
                    if ("503" in last_error or "429" in last_error) and attempt < max_retries - 1:
                        time.sleep(3 * (attempt + 1)) # Wait 3s, then 6s
                        continue
            return f"Failed to generate AI insights due to an error: {last_error}"
        except Exception as e:
            return f"Failed to generate AI insights due to an error: {str(e)}"

    @staticmethod
    def chat_with_data(messages: list, context_data: Dict[str, Any]) -> str:
        """
        Handles interactive chat queries about the dataset.
        """
        safe_results = {k: v for k, v in context_data.items() if k != 'visuals' and k != 'ai_insights'}
        context_str = json.dumps(safe_results, indent=2)
        
        system_prompt = {
            "role": "system",
            "content": f"You are an expert Data Analyst assisting a user with their dataset. Use the following statistical summary of their data to answer their questions accurately and concisely. Do not invent data.\n\nDATASET SUMMARY:\n{context_str}"
        }
        
        full_messages = [system_prompt] + messages
        
        try:
            client = AIService.get_client()
            
            if settings.ACTIVE_AI_PROVIDER.upper() == "NVIDIA" and not settings.NVIDIA_API_KEY:
                return "AI chat is currently unavailable (API key missing)."
            elif settings.ACTIVE_AI_PROVIDER.upper() == "GEMINI" and not settings.GEMINI_API_KEY:
                return "AI chat is currently unavailable (API key missing)."
                
            response = client.chat.completions.create(
                model=settings.AI_MODEL_NAME,
                messages=full_messages,
            )
            return response.choices[0].message.content
        except Exception as e:
            return f"Error connecting to AI: {str(e)}"
